version: '3'

volumes:
  postgres-data:
    driver: "local"

services:
  postgres:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=user"
      - "POSTGRES_PASSWORD=pass"