// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Softplan.MP.DistribuicaoSegundoGrau.Infrastructure.Migrations;

namespace Softplan.MP.DistribuicaoSegundoGrau.Infrastructure.Migrations.PostgreSqlSajMigrations
{
    [DbContext(typeof(PostgreSqlSajMigrationsDbContext))]
    [Migration("20211217204148_TableParametro")]
    partial class TableParametro
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Softplan.MP.DistribuicaoSegundoGrau.Application.QueryStack.Cadastros.VinculoMembroVagas.MotivoMembroVagaReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cdsitoficiante")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Ativo")
                        .HasColumnName("flsitoficiante")
                        .HasColumnType("character varying(1)")
                        .HasMaxLength(1);

                    b.Property<string>("Descricao")
                        .HasColumnName("desitoficiante")
                        .HasColumnType("character varying(40)")
                        .HasMaxLength(40);

                    b.HasKey("Id")
                        .HasName("pk_efmpsitoficiante");

                    b.ToTable("efmpsitoficiante","saj");
                });

            modelBuilder.Entity("Softplan.MP.DistribuicaoSegundoGrau.Application.QueryStack.MCD.EspecialidadeReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cdespecialidade")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Descricao")
                        .HasColumnName("deespecialidade")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id")
                        .HasName("pk_efmpespecialidade");

                    b.ToTable("efmpespecialidade","saj");
                });

            modelBuilder.Entity("Softplan.MP.DistribuicaoSegundoGrau.Application.QueryStack.TAX.AssuntoReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cdassunto")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Descricao")
                        .HasColumnName("deassunto")
                        .HasColumnType("character varying(120)")
                        .HasMaxLength(120);

                    b.HasKey("Id")
                        .HasName("pk_esajassunto");

                    b.ToTable("esajassunto","saj");
                });

            modelBuilder.Entity("Softplan.MP.DistribuicaoSegundoGrau.Application.QueryStack.TAX.ClasseReadModel", b =>
                {
                    b.Property<long>("IdClasse")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cdclasse")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Descricao")
                        .HasColumnName("declasse")
                        .HasColumnType("character varying(120)")
                        .HasMaxLength(120);

                    b.HasKey("IdClasse")
                        .HasName("pk_esajclasse");

                    b.ToTable("esajclasse","saj");
                });

            modelBuilder.Entity("Softplan.MP.DistribuicaoSegundoGrau.Application.QueryStack.TAX.ForoReadModel", b =>
                {
                    b.Property<int>("IdOrigem")
                        .HasColumnName("cdorigem")
                        .HasColumnType("integer");

                    b.Property<long>("IdForo")
                        .HasColumnName("cdforo")
                        .HasColumnType("bigint");

                    b.Property<string>("Descricao")
                        .HasColumnName("nmforo")
                        .HasColumnType("character varying(120)")
                        .HasMaxLength(120);

                    b.HasKey("IdOrigem", "IdForo")
                        .HasName("pk_efmptjforo");

                    b.ToTable("efmptjforo","saj");
                });

            modelBuilder.Entity("Softplan.MP.DistribuicaoSegundoGrau.Application.QueryStack.TAX.TarjaReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cdtarja")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Descricao")
                        .HasColumnName("detarja")
                        .HasColumnType("character varying(120)")
                        .HasMaxLength(120);

                    b.HasKey("Id")
                        .HasName("pk_esajtarja");

                    b.ToTable("esajtarja","saj");
                });

            modelBuilder.Entity("Softplan.MP.DistribuicaoSegundoGrau.Application.QueryStack.TAX.VaraReadModel", b =>
                {
                    b.Property<int>("IdOrigem")
                        .HasColumnName("cdorigem")
                        .HasColumnType("integer");

                    b.Property<long>("IdForo")
                        .HasColumnName("cdforo")
                        .HasColumnType("bigint");

                    b.Property<long>("IdVara")
                        .HasColumnName("cdvara")
                        .HasColumnType("bigint");

                    b.Property<string>("Descricao")
                        .HasColumnName("nmvara")
                        .HasColumnType("character varying(120)")
                        .HasMaxLength(120);

                    b.HasKey("IdOrigem", "IdForo", "IdVara")
                        .HasName("pk_efmptjvara");

                    b.ToTable("efmptjvara","saj");
                });

            modelBuilder.Entity("Softplan.MP.DistribuicaoSegundoGrau.Domain.Distribuicoes.Parametros.Parametro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cdparametro")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Descricao")
                        .HasColumnName("deparametro")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<int>("Desvio")
                        .HasColumnName("nutamanho")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("pk_epaddefparametro");

                    b.ToTable("epaddefparametro","saj");
                });
#pragma warning restore 612, 618
        }
    }
}
