DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210429134527_CreateVaga';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    CREATE TABLE SAJ_DSG.VAGA ( 
      ID NUMBER(10) NOT NULL,
      ORGAO_ID NUMBER(19) NOT NULL,
      TIPO_ORGAO_ID NUMBER(19) NOT NULL,
      INSTALACAO_ID NUMBER(19) NOT NULL,
      PROCURADOR_TITULAR_ID NUMBER(19) NOT NULL,
      DESCRICAO NVARCHAR2(120) NULL,
      AREA NUMBER(10) NOT NULL,
      ATIVA NUMBER(1) NOT NULL,
      REU_PRESO NUMBER(1) NOT NULL,
      DISTRIBUICAO_MESMA_VAGA NUMBER(1) NOT NULL,
      CONFIGURACOES_PREVENCAO NUMBER(1) NOT NULL,
      METADATA_UUID RAW(16) NULL,
      METADATA_ROW_VERSION BLOB NULL,
      METADATA_DATA_INCLUSAO TIMESTAMP(7) WITH TIME ZONE NULL,
      METADATA_DATA_ATUALIZACAO TIMESTAMP(7) WITH TIME ZONE NULL,
      METADATA_USUARIO_INCLUSAO NCLOB NULL,
      METADATA_USUARIO_ATUALIZACAO NCLOB NULL,
      PRIMARY KEY (ID)
    )
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210429134527_CreateVaga';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    CREATE SEQUENCE SAJ_DSG.VAGA_SEQ
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210429134527_CreateVaga';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    CREATE OR REPLACE TRIGGER SAJ_DSG.VAGA_INS_TRG
      BEFORE INSERT ON SAJ_DSG.VAGA
      FOR EACH ROW
    BEGIN
      SELECT SAJ_DSG.VAGA_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END;
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210429134527_CreateVaga';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    CREATE UNIQUE INDEX IX_VAGA_METADATA_UUID ON SAJ_DSG.VAGA (METADATA_UUID)
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210429134527_CreateVaga';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    INSERT INTO SAJ_DSG."__MigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES (''20210429134527_CreateVaga'', ''3.1.11'')
';
  END IF;
END;
/
