ALTER TABLE SAJ_DSG.MEMBRO_VAGA
DROP CONSTRAINT FK_1234200196
/
DROP TABLE SAJ_DSG.MOTIVO_MEMBRO_VAGA
/
BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SAJ_DSG.MOTIVO_MEMBRO_VAGA_SEQ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE <> -2289 THEN
      RAISE;
    END IF;
END;
/
DROP INDEX IX_N161147294
/
INSERT INTO SAJ_DSG."__MigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210604152336_RemoveMotivoMembroVaga', '3.1.11')
/
