DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210527144353_CreateMembroVaga';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    ALTER TABLE SAJ_DSG.VAGA
    MODIFY TIPO_ORGAO_ID NUMBER(10) DEFAULT NULL
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210527144353_CreateMembroVaga';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    ALTER TABLE SAJ_DSG.VAGA
    MODIFY PROCURADOR_TITULAR_ID NVARCHAR2(120) DEFAULT NULL
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210527144353_CreateMembroVaga';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    BEGIN
      EXECUTE IMMEDIATE ''ALTER TABLE SAJ_DSG.VAGA MODIFY PROCURADOR_TITULAR_ID NULL'';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE <> -1451 AND SQLCODE <> -1442 THEN
          RAISE;
        END IF;
    END;
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210527144353_CreateMembroVaga';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    ALTER TABLE SAJ_DSG.VAGA
    MODIFY ORGAO_ID NUMBER(10) DEFAULT NULL
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210527144353_CreateMembroVaga';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    ALTER TABLE SAJ_DSG.VAGA
    MODIFY INSTALACAO_ID NUMBER(10) DEFAULT NULL
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210527144353_CreateMembroVaga';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    CREATE TABLE SAJ_DSG.MOTIVO_MEMBRO_VAGA ( 
      ID NUMBER(10) NOT NULL,
      DESCRICAO NVARCHAR2(120) NULL,
      ATIVO NUMBER(1) NOT NULL,
      METADATA_UUID RAW(16) NULL,
      METADATA_ROW_VERSION BLOB NULL,
      METADATA_DATA_INCLUSAO TIMESTAMP(7) WITH TIME ZONE NULL,
      METADATA_DATA_ATUALIZACAO TIMESTAMP(7) WITH TIME ZONE NULL,
      METADATA_USUARIO_INCLUSAO NCLOB NULL,
      METADATA_USUARIO_ATUALIZACAO NCLOB NULL,
      PRIMARY KEY (ID)
    )
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210527144353_CreateMembroVaga';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    CREATE SEQUENCE SAJ_DSG.MOTIVO_MEMBRO_VAGA_SEQ
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210527144353_CreateMembroVaga';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    CREATE OR REPLACE TRIGGER SAJ_DSG.MOTIVO_MEMBRO_VAGA_INS_TRG
      BEFORE INSERT ON SAJ_DSG.MOTIVO_MEMBRO_VAGA
      FOR EACH ROW
    BEGIN
      SELECT SAJ_DSG.MOTIVO_MEMBRO_VAGA_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END;
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210527144353_CreateMembroVaga';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    CREATE TABLE SAJ_DSG.MEMBRO_VAGA ( 
      ID NUMBER(10) NOT NULL,
      ID_VAGA NUMBER(10) NOT NULL,
      ID_MEMBRO NVARCHAR2(120) NOT NULL,
      ID_MOTIVO_MEMBRO_VAGA NUMBER(10) NOT NULL,
      METADATA_UUID RAW(16) NULL,
      METADATA_ROW_VERSION BLOB NULL,
      METADATA_DATA_INCLUSAO TIMESTAMP(7) WITH TIME ZONE NULL,
      METADATA_DATA_ATUALIZACAO TIMESTAMP(7) WITH TIME ZONE NULL,
      METADATA_USUARIO_INCLUSAO NCLOB NULL,
      METADATA_USUARIO_ATUALIZACAO NCLOB NULL,
      OBSERVACAO NVARCHAR2(2000) NULL,
      DATA_INICIAL TIMESTAMP(7) WITH TIME ZONE NOT NULL,
      DATA_FINAL TIMESTAMP(7) WITH TIME ZONE NULL,
      PRIMARY KEY (ID, ID_VAGA, ID_MEMBRO),
      CONSTRAINT FK_1234200196 FOREIGN KEY (ID_MOTIVO_MEMBRO_VAGA) REFERENCES SAJ_DSG.MOTIVO_MEMBRO_VAGA (ID)
      ON DELETE CASCADE,
      CONSTRAINT FK_MEMBRO_VAGA_VAGA_ID_VAGA FOREIGN KEY (ID_VAGA) REFERENCES SAJ_DSG.VAGA (ID)
      ON DELETE CASCADE
    )
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210527144353_CreateMembroVaga';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    CREATE SEQUENCE SAJ_DSG.MEMBRO_VAGA_SEQ
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210527144353_CreateMembroVaga';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    CREATE OR REPLACE TRIGGER SAJ_DSG.MEMBRO_VAGA_INS_TRG
      BEFORE INSERT ON SAJ_DSG.MEMBRO_VAGA
      FOR EACH ROW
    BEGIN
      SELECT SAJ_DSG.MEMBRO_VAGA_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END;
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210527144353_CreateMembroVaga';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    CREATE INDEX IX_N161147294 ON SAJ_DSG.MEMBRO_VAGA (ID_MOTIVO_MEMBRO_VAGA)
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210527144353_CreateMembroVaga';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    CREATE INDEX IX_MEMBRO_VAGA_ID_VAGA ON SAJ_DSG.MEMBRO_VAGA (ID_VAGA)
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210527144353_CreateMembroVaga';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    CREATE UNIQUE INDEX IX_MEMBRO_VAGA_METADATA_UUID ON SAJ_DSG.MEMBRO_VAGA (METADATA_UUID)
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210527144353_CreateMembroVaga';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    CREATE UNIQUE INDEX IX_406354991 ON SAJ_DSG.MOTIVO_MEMBRO_VAGA (METADATA_UUID)
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210527144353_CreateMembroVaga';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    INSERT INTO SAJ_DSG."__MigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES (''20210527144353_CreateMembroVaga'', ''3.1.11'')
';
  END IF;
END;
/
