DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210512145758_CreateDistribuicaoProcesso';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    CREATE TABLE SAJ_DSG.DISTRIBUICAO_PROCESSO ( 
      PROCESSO_ID NVARCHAR2(200) NOT NULL,
      METADATA_UUID RAW(16) NULL,
      METADATA_ROW_VERSION BLOB NULL,
      METADATA_DATA_INCLUSAO TIMESTAMP(7) WITH TIME ZONE NULL,
      METADATA_DATA_ATUALIZACAO TIMESTAMP(7) WITH TIME ZONE NULL,
      METADATA_USUARIO_INCLUSAO NCLOB NULL,
      METADATA_USUARIO_ATUALIZACAO NCLOB NULL,
      PRIMARY KEY (PROCESSO_ID)
    )
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210512145758_CreateDistribuicaoProcesso';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    CREATE TABLE SAJ_DSG.DISTRIBUICAO_PROCESSO_LOG ( 
      PROCESSO_ID NVARCHAR2(200) NOT NULL,
      LOG_ID NUMBER(19) NOT NULL,
      TRANSACTION_ID RAW(16) NOT NULL,
      PAYLOAD_TYPE NVARCHAR2(200) NULL,
      PAYLOAD_SERIALIZATION_TYPE NUMBER(10) NOT NULL,
      PAYLOAD BLOB NULL,
      PRIMARY KEY (PROCESSO_ID, LOG_ID),
      CONSTRAINT FK_N1194527237 FOREIGN KEY (PROCESSO_ID) REFERENCES SAJ_DSG.DISTRIBUICAO_PROCESSO (PROCESSO_ID)
      ON DELETE CASCADE
    )
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210512145758_CreateDistribuicaoProcesso';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    CREATE SEQUENCE SAJ_DSG.DISTRIBUICAO_PROCESSO_LOG_SEQ
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210512145758_CreateDistribuicaoProcesso';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    CREATE OR REPLACE TRIGGER SAJ_DSG.TRG_1962774651
      BEFORE INSERT ON SAJ_DSG.DISTRIBUICAO_PROCESSO_LOG
      FOR EACH ROW
    BEGIN
      SELECT SAJ_DSG.DISTRIBUICAO_PROCESSO_LOG_SEQ.NEXTVAL INTO :NEW.LOG_ID FROM DUAL;
    END;
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210512145758_CreateDistribuicaoProcesso';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    CREATE UNIQUE INDEX IX_N352633229 ON SAJ_DSG.DISTRIBUICAO_PROCESSO (METADATA_UUID)
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210512145758_CreateDistribuicaoProcesso';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    CREATE INDEX IX_217771945 ON SAJ_DSG.DISTRIBUICAO_PROCESSO_LOG (PROCESSO_ID)
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210512145758_CreateDistribuicaoProcesso';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    CREATE INDEX IX_N204667741 ON SAJ_DSG.DISTRIBUICAO_PROCESSO_LOG (PROCESSO_ID, TRANSACTION_ID)
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210512145758_CreateDistribuicaoProcesso';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    INSERT INTO SAJ_DSG."__MigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES (''20210512145758_CreateDistribuicaoProcesso'', ''3.1.11'')
';
  END IF;
END;
/
