DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210510133455_CreateImpedimentoProcesso';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    CREATE TABLE SAJ_DSG.IMPEDIMENTO_PROCESSO ( 
      PROCESSO_ID NUMBER(10) NOT NULL,
      IMPEDIMENTO_ID NUMBER(10) NOT NULL,
      METADATA_UUID RAW(16) NULL,
      METADATA_ROW_VERSION BLOB NULL,
      METADATA_DATA_INCLUSAO TIMESTAMP(7) WITH TIME ZONE NULL,
      METADATA_DATA_ATUALIZACAO TIMESTAMP(7) WITH TIME ZONE NULL,
      METADATA_USUARIO_INCLUSAO NCLOB NULL,
      METADATA_USUARIO_ATUALIZACAO NCLOB NULL,
      VAGA_ID NUMBER(10) NOT NULL,
      MOTIVO NVARCHAR2(2000) NULL,
      PRIMARY KEY (PROCESSO_ID, IMPEDIMENTO_ID),
      CONSTRAINT FK_116458760 FOREIGN KEY (VAGA_ID) REFERENCES SAJ_DSG.VAGA (ID)
      ON DELETE CASCADE
    )
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210510133455_CreateImpedimentoProcesso';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    CREATE SEQUENCE SAJ_DSG.IMPEDIMENTO_PROCESSO_SEQ
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210510133455_CreateImpedimentoProcesso';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    CREATE OR REPLACE TRIGGER SAJ_DSG.IMPEDIMENTO_PROCESSO_INS_TRG
      BEFORE INSERT ON SAJ_DSG.IMPEDIMENTO_PROCESSO
      FOR EACH ROW
    BEGIN
      SELECT SAJ_DSG.IMPEDIMENTO_PROCESSO_SEQ.NEXTVAL INTO :NEW.IMPEDIMENTO_ID FROM DUAL;
    END;
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210510133455_CreateImpedimentoProcesso';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    CREATE INDEX IX_N393969318 ON SAJ_DSG.IMPEDIMENTO_PROCESSO (VAGA_ID)
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210510133455_CreateImpedimentoProcesso';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    CREATE UNIQUE INDEX IX_1762208128 ON SAJ_DSG.IMPEDIMENTO_PROCESSO (METADATA_UUID)
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210510133455_CreateImpedimentoProcesso';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    INSERT INTO SAJ_DSG."__MigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES (''20210510133455_CreateImpedimentoProcesso'', ''3.1.11'')
';
  END IF;
END;
/
