DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210429125644_CreateRegraDistribuicao';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    CREATE TABLE SAJ_DSG.REGRA_DISTRIBUICAO ( 
      ID NUMBER(10) NOT NULL,
      METADATA_UUID RAW(16) NULL,
      METADATA_ROW_VERSION BLOB NULL,
      METADATA_DATA_INCLUSAO TIMESTAMP(7) WITH TIME ZONE NULL,
      METADATA_DATA_ATUALIZACAO TIMESTAMP(7) WITH TIME ZONE NULL,
      METADATA_USUARIO_INCLUSAO NCLOB NULL,
      METADATA_USUARIO_ATUALIZACAO NCLOB NULL,
      TIPO_PROCESSO NUMBER(10) NOT NULL,
      AREA NUMBER(10) NOT NULL,
      VARIAVEL_EQUILIBRIO NUMBER(10) NOT NULL,
      ESCOPO_EQUILIBRIO NUMBER(10) NOT NULL,
      ESPECIALIDADE_ID NUMBER(10) NOT NULL,
      DESCRICAO NVARCHAR2(120) NULL,
      ATIVO NUMBER(1) NOT NULL,
      PRIMARY KEY (ID)
    )
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210429125644_CreateRegraDistribuicao';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    CREATE SEQUENCE SAJ_DSG.REGRA_DISTRIBUICAO_SEQ
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210429125644_CreateRegraDistribuicao';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    CREATE OR REPLACE TRIGGER SAJ_DSG.REGRA_DISTRIBUICAO_INS_TRG
      BEFORE INSERT ON SAJ_DSG.REGRA_DISTRIBUICAO
      FOR EACH ROW
    BEGIN
      SELECT SAJ_DSG.REGRA_DISTRIBUICAO_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END;
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210429125644_CreateRegraDistribuicao';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    CREATE TABLE SAJ_DSG.REGRA_DISTRIBUICAO_ASSUNTO ( 
      REGRA_DISTRIBUICAO_ID NUMBER(10) NOT NULL,
      ASSUNTO_ID NUMBER(10) NOT NULL,
      PRIMARY KEY (REGRA_DISTRIBUICAO_ID, ASSUNTO_ID),
      CONSTRAINT FK_N586745492 FOREIGN KEY (REGRA_DISTRIBUICAO_ID) REFERENCES SAJ_DSG.REGRA_DISTRIBUICAO (ID)
      ON DELETE CASCADE
    )
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210429125644_CreateRegraDistribuicao';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    CREATE TABLE SAJ_DSG.REGRA_DISTRIBUICAO_CLASSE ( 
      REGRA_DISTRIBUICAO_ID NUMBER(10) NOT NULL,
      CLASSE_ID NUMBER(10) NOT NULL,
      ORIGEM_ID NUMBER(10) NOT NULL,
      PRIMARY KEY (REGRA_DISTRIBUICAO_ID, CLASSE_ID),
      CONSTRAINT FK_N96322358 FOREIGN KEY (REGRA_DISTRIBUICAO_ID) REFERENCES SAJ_DSG.REGRA_DISTRIBUICAO (ID)
      ON DELETE CASCADE
    )
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210429125644_CreateRegraDistribuicao';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    CREATE TABLE SAJ_DSG.REGRA_DISTRIBUICAO_ORGAO ( 
      REGRA_DISTRIBUICAO_ID NUMBER(10) NOT NULL,
      ORGAO_JULGADOR_ID NUMBER(10) NOT NULL,
      ORIGEM_ID NUMBER(10) NOT NULL,
      PRIMARY KEY (REGRA_DISTRIBUICAO_ID, ORGAO_JULGADOR_ID),
      CONSTRAINT FK_2122819845 FOREIGN KEY (REGRA_DISTRIBUICAO_ID) REFERENCES SAJ_DSG.REGRA_DISTRIBUICAO (ID)
      ON DELETE CASCADE
    )
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210429125644_CreateRegraDistribuicao';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    CREATE TABLE SAJ_DSG.REGRA_DISTRIBUICAO_TARJA ( 
      REGRA_DISTRIBUICAO_ID NUMBER(10) NOT NULL,
      TARJA_ID NUMBER(10) NOT NULL,
      PRIMARY KEY (REGRA_DISTRIBUICAO_ID, TARJA_ID),
      CONSTRAINT FK_1417155453 FOREIGN KEY (REGRA_DISTRIBUICAO_ID) REFERENCES SAJ_DSG.REGRA_DISTRIBUICAO (ID)
      ON DELETE CASCADE
    )
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210429125644_CreateRegraDistribuicao';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    CREATE TABLE SAJ_DSG.REGRA_DISTRIBUICAO_UNIDADE ( 
      REGRA_DISTRIBUICAO_ID NUMBER(10) NOT NULL,
      UNIDADE_ID NUMBER(10) NOT NULL,
      ORIGEM_ID NUMBER(10) NOT NULL,
      ORGAO_JULGADOR_ID NUMBER(10) NOT NULL,
      PRIMARY KEY (REGRA_DISTRIBUICAO_ID, UNIDADE_ID),
      CONSTRAINT FK_N1282032833 FOREIGN KEY (REGRA_DISTRIBUICAO_ID) REFERENCES SAJ_DSG.REGRA_DISTRIBUICAO (ID)
      ON DELETE CASCADE
    )
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210429125644_CreateRegraDistribuicao';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    CREATE UNIQUE INDEX IX_N221632554 ON SAJ_DSG.REGRA_DISTRIBUICAO (METADATA_UUID)
';
  END IF;
END;
/
DECLARE
  pCount NUMBER;
BEGIN
  pCount := 0;
  SELECT count(*) INTO pCount FROM SAJ_DSG."__MigrationsHistory" WHERE "MigrationId" = '20210429125644_CreateRegraDistribuicao';
  IF (pCount <> 1) THEN
    EXECUTE IMMEDIATE '
    INSERT INTO SAJ_DSG."__MigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES (''20210429125644_CreateRegraDistribuicao'', ''3.1.11'')
';
  END IF;
END;
/
