
DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saj_dsg."__MigrationsHistory" WHERE "MigrationId" = '20211209182844_Create_Excecao_Vaga') THEN
    CREATE TABLE saj_dsg.excecao_vaga (
        id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        metadata_uuid uuid NULL,
        metadata_row_version bytea NULL,
        metadata_data_inclusao timestamp with time zone NULL,
        metadata_data_atualizacao timestamp with time zone NULL,
        metadata_usuario_inclusao text NULL,
        metadata_usuario_atualizacao text NULL,
        vaga_id integer NOT NULL,
        classe_id integer NULL,
        assunto_id integer NULL,
        especialidade_id integer NULL,
        origem_id integer NULL,
        unidade_id integer NULL,
        orgao_julgador_id integer NULL,
        CONSTRAINT pk_excecao_vaga PRIMARY KEY (id)
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saj_dsg."__MigrationsHistory" WHERE "MigrationId" = '20211209182844_Create_Excecao_Vaga') THEN
    CREATE UNIQUE INDEX ix_excecao_vaga_metadata_uuid ON saj_dsg.excecao_vaga (metadata_uuid);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saj_dsg."__MigrationsHistory" WHERE "MigrationId" = '20211209182844_Create_Excecao_Vaga') THEN
    INSERT INTO saj_dsg."__MigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20211209182844_Create_Excecao_Vaga', '3.1.17');
    END IF;
END $$;
