
DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saj_dsg."__MigrationsHistory" WHERE "MigrationId" = '20210527144103_CreateMembroVaga') THEN
    ALTER TABLE saj_dsg.vaga ALTER COLUMN tipo_orgao_id TYPE integer;
    ALTER TABLE saj_dsg.vaga ALTER COLUMN tipo_orgao_id SET NOT NULL;
    ALTER TABLE saj_dsg.vaga ALTER COLUMN tipo_orgao_id DROP DEFAULT;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saj_dsg."__MigrationsHistory" WHERE "MigrationId" = '20210527144103_CreateMembroVaga') THEN
    ALTER TABLE saj_dsg.vaga ALTER COLUMN procurador_titular_id TYPE character varying(120);
    ALTER TABLE saj_dsg.vaga ALTER COLUMN procurador_titular_id DROP NOT NULL;
    ALTER TABLE saj_dsg.vaga ALTER COLUMN procurador_titular_id DROP DEFAULT;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saj_dsg."__MigrationsHistory" WHERE "MigrationId" = '20210527144103_CreateMembroVaga') THEN
    ALTER TABLE saj_dsg.vaga ALTER COLUMN orgao_id TYPE integer;
    ALTER TABLE saj_dsg.vaga ALTER COLUMN orgao_id SET NOT NULL;
    ALTER TABLE saj_dsg.vaga ALTER COLUMN orgao_id DROP DEFAULT;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saj_dsg."__MigrationsHistory" WHERE "MigrationId" = '20210527144103_CreateMembroVaga') THEN
    ALTER TABLE saj_dsg.vaga ALTER COLUMN instalacao_id TYPE integer;
    ALTER TABLE saj_dsg.vaga ALTER COLUMN instalacao_id SET NOT NULL;
    ALTER TABLE saj_dsg.vaga ALTER COLUMN instalacao_id DROP DEFAULT;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saj_dsg."__MigrationsHistory" WHERE "MigrationId" = '20210527144103_CreateMembroVaga') THEN
    CREATE TABLE saj_dsg.motivo_membro_vaga (
        id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        descricao character varying(120) NULL,
        ativo boolean NOT NULL,
        metadata_uuid uuid NULL,
        metadata_row_version bytea NULL,
        metadata_data_inclusao timestamp with time zone NULL,
        metadata_data_atualizacao timestamp with time zone NULL,
        metadata_usuario_inclusao text NULL,
        metadata_usuario_atualizacao text NULL,
        CONSTRAINT pk_motivo_membro_vaga PRIMARY KEY (id)
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saj_dsg."__MigrationsHistory" WHERE "MigrationId" = '20210527144103_CreateMembroVaga') THEN
    CREATE TABLE saj_dsg.membro_vaga (
        id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        id_vaga integer NOT NULL,
        id_membro character varying(120) NOT NULL,
        id_motivo_membro_vaga integer NOT NULL,
        metadata_uuid uuid NULL,
        metadata_row_version bytea NULL,
        metadata_data_inclusao timestamp with time zone NULL,
        metadata_data_atualizacao timestamp with time zone NULL,
        metadata_usuario_inclusao text NULL,
        metadata_usuario_atualizacao text NULL,
        observacao character varying(2000) NULL,
        data_inicial timestamp with time zone NOT NULL,
        data_final timestamp with time zone NULL,
        CONSTRAINT pk_membro_vaga PRIMARY KEY (id, id_vaga, id_membro),
        CONSTRAINT fk_membro_vaga_motivo_membro_vaga_id_motivo_membro_vaga FOREIGN KEY (id_motivo_membro_vaga) REFERENCES saj_dsg.motivo_membro_vaga (id) ON DELETE CASCADE,
        CONSTRAINT fk_membro_vaga_vaga_id_vaga FOREIGN KEY (id_vaga) REFERENCES saj_dsg.vaga (id) ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saj_dsg."__MigrationsHistory" WHERE "MigrationId" = '20210527144103_CreateMembroVaga') THEN
    CREATE INDEX ix_membro_vaga_id_motivo_membro_vaga ON saj_dsg.membro_vaga (id_motivo_membro_vaga);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saj_dsg."__MigrationsHistory" WHERE "MigrationId" = '20210527144103_CreateMembroVaga') THEN
    CREATE INDEX ix_membro_vaga_id_vaga ON saj_dsg.membro_vaga (id_vaga);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saj_dsg."__MigrationsHistory" WHERE "MigrationId" = '20210527144103_CreateMembroVaga') THEN
    CREATE UNIQUE INDEX ix_membro_vaga_metadata_uuid ON saj_dsg.membro_vaga (metadata_uuid);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saj_dsg."__MigrationsHistory" WHERE "MigrationId" = '20210527144103_CreateMembroVaga') THEN
    CREATE UNIQUE INDEX ix_motivo_membro_vaga_metadata_uuid ON saj_dsg.motivo_membro_vaga (metadata_uuid);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saj_dsg."__MigrationsHistory" WHERE "MigrationId" = '20210527144103_CreateMembroVaga') THEN
    INSERT INTO saj_dsg."__MigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20210527144103_CreateMembroVaga', '3.1.11');
    END IF;
END $$;
