
DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saj_dsg."__MigrationsHistory" WHERE "MigrationId" = '20210429134923_CreateVaga') THEN
    CREATE TABLE saj_dsg.vaga (
        id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        orgao_id bigint NOT NULL,
        tipo_orgao_id bigint NOT NULL,
        instalacao_id bigint NOT NULL,
        procurador_titular_id bigint NOT NULL,
        descricao character varying(120) NULL,
        area integer NOT NULL,
        ativa boolean NOT NULL,
        reu_preso boolean NOT NULL,
        distribuicao_mesma_vaga boolean NOT NULL,
        configuracoes_prevencao boolean NOT NULL,
        metadata_uuid uuid NULL,
        metadata_row_version bytea NULL,
        metadata_data_inclusao timestamp with time zone NULL,
        metadata_data_atualizacao timestamp with time zone NULL,
        metadata_usuario_inclusao text NULL,
        metadata_usuario_atualizacao text NULL,
        CONSTRAINT pk_vaga PRIMARY KEY (id)
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saj_dsg."__MigrationsHistory" WHERE "MigrationId" = '20210429134923_CreateVaga') THEN
    CREATE UNIQUE INDEX ix_vaga_metadata_uuid ON saj_dsg.vaga (metadata_uuid);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saj_dsg."__MigrationsHistory" WHERE "MigrationId" = '20210429134923_CreateVaga') THEN
    INSERT INTO saj_dsg."__MigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20210429134923_CreateVaga', '3.1.11');
    END IF;
END $$;
