
DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saj_dsg."__MigrationsHistory" WHERE "MigrationId" = '20210429125051_CreateRegraDistribuicao') THEN
    CREATE SCHEMA IF NOT EXISTS saj_dsg;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saj_dsg."__MigrationsHistory" WHERE "MigrationId" = '20210429125051_CreateRegraDistribuicao') THEN
    CREATE TABLE saj_dsg.regra_distribuicao (
        id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        metadata_uuid uuid NULL,
        metadata_row_version bytea NULL,
        metadata_data_inclusao timestamp with time zone NULL,
        metadata_data_atualizacao timestamp with time zone NULL,
        metadata_usuario_inclusao text NULL,
        metadata_usuario_atualizacao text NULL,
        tipo_processo integer NOT NULL,
        area integer NOT NULL,
        variavel_equilibrio integer NOT NULL,
        escopo_equilibrio integer NOT NULL,
        especialidade_id integer NOT NULL,
        descricao character varying(120) NULL,
        ativo boolean NOT NULL,
        CONSTRAINT pk_regra_distribuicao PRIMARY KEY (id)
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saj_dsg."__MigrationsHistory" WHERE "MigrationId" = '20210429125051_CreateRegraDistribuicao') THEN
    CREATE TABLE saj_dsg.regra_distribuicao_assunto (
        regra_distribuicao_id integer NOT NULL,
        assunto_id integer NOT NULL,
        CONSTRAINT pk_regra_distribuicao_assunto PRIMARY KEY (regra_distribuicao_id, assunto_id),
        CONSTRAINT "fk_regra_distribuicao_assunto_regra_distribuicao_regra_distrib~" FOREIGN KEY (regra_distribuicao_id) REFERENCES saj_dsg.regra_distribuicao (id) ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saj_dsg."__MigrationsHistory" WHERE "MigrationId" = '20210429125051_CreateRegraDistribuicao') THEN
    CREATE TABLE saj_dsg.regra_distribuicao_classe (
        regra_distribuicao_id integer NOT NULL,
        classe_id integer NOT NULL,
        origem_id integer NOT NULL,
        CONSTRAINT pk_regra_distribuicao_classe PRIMARY KEY (regra_distribuicao_id, classe_id),
        CONSTRAINT "fk_regra_distribuicao_classe_regra_distribuicao_regra_distribu~" FOREIGN KEY (regra_distribuicao_id) REFERENCES saj_dsg.regra_distribuicao (id) ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saj_dsg."__MigrationsHistory" WHERE "MigrationId" = '20210429125051_CreateRegraDistribuicao') THEN
    CREATE TABLE saj_dsg.regra_distribuicao_orgao (
        regra_distribuicao_id integer NOT NULL,
        orgao_julgador_id integer NOT NULL,
        origem_id integer NOT NULL,
        CONSTRAINT pk_regra_distribuicao_orgao PRIMARY KEY (regra_distribuicao_id, orgao_julgador_id),
        CONSTRAINT "fk_regra_distribuicao_orgao_regra_distribuicao_regra_distribui~" FOREIGN KEY (regra_distribuicao_id) REFERENCES saj_dsg.regra_distribuicao (id) ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saj_dsg."__MigrationsHistory" WHERE "MigrationId" = '20210429125051_CreateRegraDistribuicao') THEN
    CREATE TABLE saj_dsg.regra_distribuicao_tarja (
        regra_distribuicao_id integer NOT NULL,
        tarja_id integer NOT NULL,
        CONSTRAINT pk_regra_distribuicao_tarja PRIMARY KEY (regra_distribuicao_id, tarja_id),
        CONSTRAINT "fk_regra_distribuicao_tarja_regra_distribuicao_regra_distribui~" FOREIGN KEY (regra_distribuicao_id) REFERENCES saj_dsg.regra_distribuicao (id) ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saj_dsg."__MigrationsHistory" WHERE "MigrationId" = '20210429125051_CreateRegraDistribuicao') THEN
    CREATE TABLE saj_dsg.regra_distribuicao_unidade (
        regra_distribuicao_id integer NOT NULL,
        unidade_id integer NOT NULL,
        origem_id integer NOT NULL,
        orgao_julgador_id integer NOT NULL,
        CONSTRAINT pk_regra_distribuicao_unidade PRIMARY KEY (regra_distribuicao_id, unidade_id),
        CONSTRAINT "fk_regra_distribuicao_unidade_regra_distribuicao_regra_distrib~" FOREIGN KEY (regra_distribuicao_id) REFERENCES saj_dsg.regra_distribuicao (id) ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saj_dsg."__MigrationsHistory" WHERE "MigrationId" = '20210429125051_CreateRegraDistribuicao') THEN
    CREATE UNIQUE INDEX ix_regra_distribuicao_metadata_uuid ON saj_dsg.regra_distribuicao (metadata_uuid);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saj_dsg."__MigrationsHistory" WHERE "MigrationId" = '20210429125051_CreateRegraDistribuicao') THEN
    INSERT INTO saj_dsg."__MigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20210429125051_CreateRegraDistribuicao', '3.1.11');
    END IF;
END $$;
