
DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saj_dsg."__MigrationsHistory" WHERE "MigrationId" = '20210512144541_CreateDistribuicaoProcesso') THEN
    CREATE TABLE saj_dsg.distribuicao_processo (
        processo_id character varying(200) NOT NULL,
        metadata_uuid uuid NULL,
        metadata_row_version bytea NULL,
        metadata_data_inclusao timestamp with time zone NULL,
        metadata_data_atualizacao timestamp with time zone NULL,
        metadata_usuario_inclusao text NULL,
        metadata_usuario_atualizacao text NULL,
        CONSTRAINT pk_distribuicao_processo PRIMARY KEY (processo_id)
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saj_dsg."__MigrationsHistory" WHERE "MigrationId" = '20210512144541_CreateDistribuicaoProcesso') THEN
    CREATE TABLE saj_dsg.distribuicao_processo_log (
        processo_id character varying(200) NOT NULL,
        log_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        transaction_id uuid NOT NULL,
        payload_type character varying(200) NULL,
        payload_serialization_type integer NOT NULL,
        payload bytea NULL,
        CONSTRAINT pk_distribuicao_processo_log PRIMARY KEY (processo_id, log_id),
        CONSTRAINT fk_distribuicao_processo_log_distribuicao_processo_processo_id FOREIGN KEY (processo_id) REFERENCES saj_dsg.distribuicao_processo (processo_id) ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saj_dsg."__MigrationsHistory" WHERE "MigrationId" = '20210512144541_CreateDistribuicaoProcesso') THEN
    CREATE UNIQUE INDEX ix_distribuicao_processo_metadata_uuid ON saj_dsg.distribuicao_processo (metadata_uuid);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saj_dsg."__MigrationsHistory" WHERE "MigrationId" = '20210512144541_CreateDistribuicaoProcesso') THEN
    CREATE INDEX distribuicao_processo_log_processo ON saj_dsg.distribuicao_processo_log (processo_id);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saj_dsg."__MigrationsHistory" WHERE "MigrationId" = '20210512144541_CreateDistribuicaoProcesso') THEN
    CREATE INDEX distribuicao_processo_log_processo_transactionid ON saj_dsg.distribuicao_processo_log (processo_id, transaction_id);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saj_dsg."__MigrationsHistory" WHERE "MigrationId" = '20210512144541_CreateDistribuicaoProcesso') THEN
    INSERT INTO saj_dsg."__MigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20210512144541_CreateDistribuicaoProcesso', '3.1.11');
    END IF;
END $$;
