
DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saj_dsg."__MigrationsHistory" WHERE "MigrationId" = '20220105231223_CreateImpedimentoDistribuicaoLog') THEN
    CREATE TABLE saj_dsg.impedimento_distribuicao_log (
        log_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        processo_id character varying(200) NOT NULL,
        transaction_id uuid NOT NULL,
        tipo_distribuicao integer NOT NULL,
        payload_type character varying(200) NULL,
        payload_serialization_type integer NOT NULL,
        payload bytea NULL,
        metadata_uuid uuid NULL,
        metadata_row_version bytea NULL,
        metadata_data_inclusao timestamp with time zone NULL,
        metadata_data_atualizacao timestamp with time zone NULL,
        metadata_usuario_inclusao text NULL,
        metadata_usuario_atualizacao text NULL,
        CONSTRAINT pk_impedimento_distribuicao_log PRIMARY KEY (log_id)
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saj_dsg."__MigrationsHistory" WHERE "MigrationId" = '20220105231223_CreateImpedimentoDistribuicaoLog') THEN
    CREATE INDEX impedimento_distribuicao_log_processo ON saj_dsg.impedimento_distribuicao_log (processo_id);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saj_dsg."__MigrationsHistory" WHERE "MigrationId" = '20220105231223_CreateImpedimentoDistribuicaoLog') THEN
    CREATE INDEX impedimento_distribuicao_log_processo_transactionid ON saj_dsg.impedimento_distribuicao_log (processo_id, transaction_id);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saj_dsg."__MigrationsHistory" WHERE "MigrationId" = '20220105231223_CreateImpedimentoDistribuicaoLog') THEN
    CREATE UNIQUE INDEX ix_impedimento_distribuicao_log_metadata_uuid ON saj_dsg.impedimento_distribuicao_log (metadata_uuid);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM saj_dsg."__MigrationsHistory" WHERE "MigrationId" = '20220105231223_CreateImpedimentoDistribuicaoLog') THEN
    INSERT INTO saj_dsg."__MigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20220105231223_CreateImpedimentoDistribuicaoLog', '3.1.17');
    END IF;
END $$;
