// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Softplan.MP.DistribuicaoSegundoGrau.Infrastructure.Migrations;

namespace Softplan.MP.DistribuicaoSegundoGrau.Infrastructure.Migrations.OracleSajMigrations
{
    [DbContext(typeof(OracleSajMigrationsDbContext))]
    [Migration("20210720180325_UpdateRegraClasse")]
    partial class UpdateRegraClasse
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11");

            modelBuilder.Entity("Softplan.MP.DistribuicaoSegundoGrau.Application.QueryStack.Cadastros.VinculoMembroVagas.MotivoMembroVagaReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CDSITOFICIANTE")
                        .HasColumnType("int");

                    b.Property<string>("Ativo")
                        .HasColumnName("FLSITOFICIANTE")
                        .HasColumnType("nvarchar2(1)")
                        .HasMaxLength(1);

                    b.Property<string>("Descricao")
                        .HasColumnName("DESITOFICIANTE")
                        .HasColumnType("nvarchar2(40)")
                        .HasMaxLength(40);

                    b.HasKey("Id");

                    b.ToTable("EFMPSITOFICIANTE","SAJ");
                });

            modelBuilder.Entity("Softplan.MP.DistribuicaoSegundoGrau.Application.QueryStack.MCD.EspecialidadeReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CDESPECIALIDADE")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnName("DEESPECIALIDADE")
                        .HasColumnType("nvarchar2(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("EFMPESPECIALIDADE","SAJ");
                });

            modelBuilder.Entity("Softplan.MP.DistribuicaoSegundoGrau.Application.QueryStack.TAX.AssuntoReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CDASSUNTO")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnName("DEASSUNTO")
                        .HasColumnType("nvarchar2(120)")
                        .HasMaxLength(120);

                    b.HasKey("Id");

                    b.ToTable("ESAJASSUNTO","SAJ");
                });

            modelBuilder.Entity("Softplan.MP.DistribuicaoSegundoGrau.Application.QueryStack.TAX.ClasseReadModel", b =>
                {
                    b.Property<long>("IdClasse")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CDCLASSE")
                        .HasColumnType("int64");

                    b.Property<string>("Descricao")
                        .HasColumnName("DECLASSE")
                        .HasColumnType("nvarchar2(120)")
                        .HasMaxLength(120);

                    b.HasKey("IdClasse");

                    b.ToTable("ESAJCLASSE","SAJ");
                });

            modelBuilder.Entity("Softplan.MP.DistribuicaoSegundoGrau.Application.QueryStack.TAX.ForoReadModel", b =>
                {
                    b.Property<int>("IdOrigem")
                        .HasColumnName("CDORIGEM")
                        .HasColumnType("int");

                    b.Property<long>("IdForo")
                        .HasColumnName("CDFORO")
                        .HasColumnType("int64");

                    b.Property<string>("Descricao")
                        .HasColumnName("NMFORO")
                        .HasColumnType("nvarchar2(120)")
                        .HasMaxLength(120);

                    b.HasKey("IdOrigem", "IdForo");

                    b.ToTable("EFMPTJFORO","SAJ");
                });

            modelBuilder.Entity("Softplan.MP.DistribuicaoSegundoGrau.Application.QueryStack.TAX.TarjaReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CDTARJA")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnName("DETARJA")
                        .HasColumnType("nvarchar2(120)")
                        .HasMaxLength(120);

                    b.HasKey("Id");

                    b.ToTable("ESAJTARJA","SAJ");
                });

            modelBuilder.Entity("Softplan.MP.DistribuicaoSegundoGrau.Application.QueryStack.TAX.VaraReadModel", b =>
                {
                    b.Property<int>("IdOrigem")
                        .HasColumnName("CDORIGEM")
                        .HasColumnType("int");

                    b.Property<long>("IdForo")
                        .HasColumnName("CDFORO")
                        .HasColumnType("int64");

                    b.Property<long>("IdVara")
                        .HasColumnName("CDVARA")
                        .HasColumnType("int64");

                    b.Property<string>("Descricao")
                        .HasColumnName("NMVARA")
                        .HasColumnType("nvarchar2(120)")
                        .HasMaxLength(120);

                    b.HasKey("IdOrigem", "IdForo", "IdVara");

                    b.ToTable("EFMPTJVARA","SAJ");
                });
#pragma warning restore 612, 618
        }
    }
}
