// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Softplan.MP.DistribuicaoSegundoGrau.Infrastructure.Migrations;

namespace Softplan.MP.DistribuicaoSegundoGrau.Infrastructure.Migrations.OracleSajMigrations
{
    [DbContext(typeof(OracleSajMigrationsDbContext))]
    [Migration("20210506172950_CreateTaxonomia")]
    partial class CreateTaxonomia
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11");

            modelBuilder.Entity("Softplan.MP.DistribuicaoSegundoGrau.Application.QueryStack.Taxonomia.AssuntoReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CDASSUNTO")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnName("DEASSUNTO")
                        .HasColumnType("nvarchar2(120)")
                        .HasMaxLength(120);

                    b.HasKey("Id");

                    b.ToTable("ESAJASSUNTO","SAJ");
                });

            modelBuilder.Entity("Softplan.MP.DistribuicaoSegundoGrau.Application.QueryStack.Taxonomia.ClasseReadModel", b =>
                {
                    b.Property<int>("IdOrigem")
                        .HasColumnName("CDORIGEM")
                        .HasColumnType("int");

                    b.Property<int>("IdClasse")
                        .HasColumnName("CDCLASSE")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnName("DECLASSE")
                        .HasColumnType("nvarchar2(120)")
                        .HasMaxLength(120);

                    b.HasKey("IdOrigem", "IdClasse");

                    b.ToTable("EFMPTJCLASSE","SAJ");
                });

            modelBuilder.Entity("Softplan.MP.DistribuicaoSegundoGrau.Application.QueryStack.Taxonomia.ForoReadModel", b =>
                {
                    b.Property<int>("IdOrigem")
                        .HasColumnName("CDORIGEM")
                        .HasColumnType("int");

                    b.Property<int>("IdForo")
                        .HasColumnName("CDFORO")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnName("NMFORO")
                        .HasColumnType("nvarchar2(120)")
                        .HasMaxLength(120);

                    b.HasKey("IdOrigem", "IdForo");

                    b.ToTable("EFMPTJFORO","SAJ");
                });

            modelBuilder.Entity("Softplan.MP.DistribuicaoSegundoGrau.Application.QueryStack.Taxonomia.TarjaReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CDTARJA")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnName("DETARJA")
                        .HasColumnType("nvarchar2(120)")
                        .HasMaxLength(120);

                    b.HasKey("Id");

                    b.ToTable("ESAJTARJA","SAJ");
                });

            modelBuilder.Entity("Softplan.MP.DistribuicaoSegundoGrau.Application.QueryStack.Taxonomia.VaraReadModel", b =>
                {
                    b.Property<int>("IdOrigem")
                        .HasColumnName("CDORIGEM")
                        .HasColumnType("int");

                    b.Property<int>("IdForo")
                        .HasColumnName("CDFORO")
                        .HasColumnType("int");

                    b.Property<int>("IdVara")
                        .HasColumnName("CDVARA")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnName("NMVARA")
                        .HasColumnType("nvarchar2(120)")
                        .HasMaxLength(120);

                    b.HasKey("IdOrigem", "IdForo", "IdVara");

                    b.ToTable("EFMPTJVARA","SAJ");
                });
#pragma warning restore 612, 618
        }
    }
}
