// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Distribuicoes/Messages/Protos/ProcessoFoiDistribuidoPorPrevencao.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using System.Diagnostics.CodeAnalysis;
using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Softplan.MP.DistribuicaoSegundoGrau.Domain.Distribuicoes.Messages.Protos {

  [ExcludeFromCodeCoverage]
  /// <summary>Holder for reflection information generated from Distribuicoes/Messages/Protos/ProcessoFoiDistribuidoPorPrevencao.proto</summary>
  public static partial class ProcessoFoiDistribuidoPorPrevencaoReflection {

    #region Descriptor
    /// <summary>File descriptor for Distribuicoes/Messages/Protos/ProcessoFoiDistribuidoPorPrevencao.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProcessoFoiDistribuidoPorPrevencaoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CkZEaXN0cmlidWljb2VzL01lc3NhZ2VzL1Byb3Rvcy9Qcm9jZXNzb0ZvaURp",
            "c3RyaWJ1aWRvUG9yUHJldmVuY2FvLnByb3RvGh9nb29nbGUvcHJvdG9idWYv",
            "dGltZXN0YW1wLnByb3RvIn8KIlByb2Nlc3NvRm9pRGlzdHJpYnVpZG9Qb3JQ",
            "cmV2ZW5jYW8SEwoLaWRfcHJvY2Vzc28YASABKAkSDwoHdXN1YXJpbxgCIAEo",
            "CRIzCg9kYXRhX29jb3JyZW5jaWEYAyABKAsyGi5nb29nbGUucHJvdG9idWYu",
            "VGltZXN0YW1wQkuqAkhTb2Z0cGxhbi5NUC5EaXN0cmlidWljYW9TZWd1bmRv",
            "R3JhdS5Eb21haW4uRGlzdHJpYnVpY29lcy5NZXNzYWdlcy5Qcm90b3NiBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Softplan.MP.DistribuicaoSegundoGrau.Domain.Distribuicoes.Messages.Protos.ProcessoFoiDistribuidoPorPrevencao), global::Softplan.MP.DistribuicaoSegundoGrau.Domain.Distribuicoes.Messages.Protos.ProcessoFoiDistribuidoPorPrevencao.Parser, new[]{ "IdProcesso", "Usuario", "DataOcorrencia" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ProcessoFoiDistribuidoPorPrevencao : pb::IMessage<ProcessoFoiDistribuidoPorPrevencao>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProcessoFoiDistribuidoPorPrevencao> _parser = new pb::MessageParser<ProcessoFoiDistribuidoPorPrevencao>(() => new ProcessoFoiDistribuidoPorPrevencao());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ProcessoFoiDistribuidoPorPrevencao> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Softplan.MP.DistribuicaoSegundoGrau.Domain.Distribuicoes.Messages.Protos.ProcessoFoiDistribuidoPorPrevencaoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProcessoFoiDistribuidoPorPrevencao() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProcessoFoiDistribuidoPorPrevencao(ProcessoFoiDistribuidoPorPrevencao other) : this() {
      idProcesso_ = other.idProcesso_;
      usuario_ = other.usuario_;
      dataOcorrencia_ = other.dataOcorrencia_ != null ? other.dataOcorrencia_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProcessoFoiDistribuidoPorPrevencao Clone() {
      return new ProcessoFoiDistribuidoPorPrevencao(this);
    }

    /// <summary>Field number for the "id_processo" field.</summary>
    public const int IdProcessoFieldNumber = 1;
    private string idProcesso_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string IdProcesso {
      get { return idProcesso_; }
      set {
        idProcesso_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "usuario" field.</summary>
    public const int UsuarioFieldNumber = 2;
    private string usuario_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Usuario {
      get { return usuario_; }
      set {
        usuario_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "data_ocorrencia" field.</summary>
    public const int DataOcorrenciaFieldNumber = 3;
    private global::Google.Protobuf.WellKnownTypes.Timestamp dataOcorrencia_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp DataOcorrencia {
      get { return dataOcorrencia_; }
      set {
        dataOcorrencia_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ProcessoFoiDistribuidoPorPrevencao);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ProcessoFoiDistribuidoPorPrevencao other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IdProcesso != other.IdProcesso) return false;
      if (Usuario != other.Usuario) return false;
      if (!object.Equals(DataOcorrencia, other.DataOcorrencia)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (IdProcesso.Length != 0) hash ^= IdProcesso.GetHashCode();
      if (Usuario.Length != 0) hash ^= Usuario.GetHashCode();
      if (dataOcorrencia_ != null) hash ^= DataOcorrencia.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (IdProcesso.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(IdProcesso);
      }
      if (Usuario.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Usuario);
      }
      if (dataOcorrencia_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(DataOcorrencia);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (IdProcesso.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(IdProcesso);
      }
      if (Usuario.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Usuario);
      }
      if (dataOcorrencia_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(DataOcorrencia);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (IdProcesso.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdProcesso);
      }
      if (Usuario.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Usuario);
      }
      if (dataOcorrencia_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DataOcorrencia);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ProcessoFoiDistribuidoPorPrevencao other) {
      if (other == null) {
        return;
      }
      if (other.IdProcesso.Length != 0) {
        IdProcesso = other.IdProcesso;
      }
      if (other.Usuario.Length != 0) {
        Usuario = other.Usuario;
      }
      if (other.dataOcorrencia_ != null) {
        if (dataOcorrencia_ == null) {
          DataOcorrencia = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        DataOcorrencia.MergeFrom(other.DataOcorrencia);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            IdProcesso = input.ReadString();
            break;
          }
          case 18: {
            Usuario = input.ReadString();
            break;
          }
          case 26: {
            if (dataOcorrencia_ == null) {
              DataOcorrencia = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(DataOcorrencia);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            IdProcesso = input.ReadString();
            break;
          }
          case 18: {
            Usuario = input.ReadString();
            break;
          }
          case 26: {
            if (dataOcorrencia_ == null) {
              DataOcorrencia = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(DataOcorrencia);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
