// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Distribuicoes/Messages/Protos/RemessaProcessoFoiAgendada.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using System.Diagnostics.CodeAnalysis;
using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Softplan.MP.DistribuicaoSegundoGrau.Domain.Distribuicoes.Messages.Protos {

  [ExcludeFromCodeCoverage]
  /// <summary>Holder for reflection information generated from Distribuicoes/Messages/Protos/RemessaProcessoFoiAgendada.proto</summary>
  public static partial class RemessaProcessoFoiAgendadaReflection {

    #region Descriptor
    /// <summary>File descriptor for Distribuicoes/Messages/Protos/RemessaProcessoFoiAgendada.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RemessaProcessoFoiAgendadaReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cj5EaXN0cmlidWljb2VzL01lc3NhZ2VzL1Byb3Rvcy9SZW1lc3NhUHJvY2Vz",
            "c29Gb2lBZ2VuZGFkYS5wcm90byKtAQoaUmVtZXNzYVByb2Nlc3NvRm9pQWdl",
            "bmRhZGESEwoLaWRfcHJvY2Vzc28YASABKAkSGwoTY29kaWdvX2Zvcm9fZGVz",
            "dGlubxgCIAEoBRIhChljb2RpZ29fdGlwb19sb2NhbF9kZXN0aW5vGAMgASgF",
            "EhwKFGNvZGlnb19sb2NhbF9kZXN0aW5vGAQgASgFEhwKFGlkX2xvdGVfZGlz",
            "dHJpYnVpY2FvGAUgASgDQkuqAkhTb2Z0cGxhbi5NUC5EaXN0cmlidWljYW9T",
            "ZWd1bmRvR3JhdS5Eb21haW4uRGlzdHJpYnVpY29lcy5NZXNzYWdlcy5Qcm90",
            "b3NiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Softplan.MP.DistribuicaoSegundoGrau.Domain.Distribuicoes.Messages.Protos.RemessaProcessoFoiAgendada), global::Softplan.MP.DistribuicaoSegundoGrau.Domain.Distribuicoes.Messages.Protos.RemessaProcessoFoiAgendada.Parser, new[]{ "IdProcesso", "CodigoForoDestino", "CodigoTipoLocalDestino", "CodigoLocalDestino", "IdLoteDistribuicao" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class RemessaProcessoFoiAgendada : pb::IMessage<RemessaProcessoFoiAgendada>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RemessaProcessoFoiAgendada> _parser = new pb::MessageParser<RemessaProcessoFoiAgendada>(() => new RemessaProcessoFoiAgendada());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RemessaProcessoFoiAgendada> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Softplan.MP.DistribuicaoSegundoGrau.Domain.Distribuicoes.Messages.Protos.RemessaProcessoFoiAgendadaReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RemessaProcessoFoiAgendada() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RemessaProcessoFoiAgendada(RemessaProcessoFoiAgendada other) : this() {
      idProcesso_ = other.idProcesso_;
      codigoForoDestino_ = other.codigoForoDestino_;
      codigoTipoLocalDestino_ = other.codigoTipoLocalDestino_;
      codigoLocalDestino_ = other.codigoLocalDestino_;
      idLoteDistribuicao_ = other.idLoteDistribuicao_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RemessaProcessoFoiAgendada Clone() {
      return new RemessaProcessoFoiAgendada(this);
    }

    /// <summary>Field number for the "id_processo" field.</summary>
    public const int IdProcessoFieldNumber = 1;
    private string idProcesso_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string IdProcesso {
      get { return idProcesso_; }
      set {
        idProcesso_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "codigo_foro_destino" field.</summary>
    public const int CodigoForoDestinoFieldNumber = 2;
    private int codigoForoDestino_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CodigoForoDestino {
      get { return codigoForoDestino_; }
      set {
        codigoForoDestino_ = value;
      }
    }

    /// <summary>Field number for the "codigo_tipo_local_destino" field.</summary>
    public const int CodigoTipoLocalDestinoFieldNumber = 3;
    private int codigoTipoLocalDestino_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CodigoTipoLocalDestino {
      get { return codigoTipoLocalDestino_; }
      set {
        codigoTipoLocalDestino_ = value;
      }
    }

    /// <summary>Field number for the "codigo_local_destino" field.</summary>
    public const int CodigoLocalDestinoFieldNumber = 4;
    private int codigoLocalDestino_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CodigoLocalDestino {
      get { return codigoLocalDestino_; }
      set {
        codigoLocalDestino_ = value;
      }
    }

    /// <summary>Field number for the "id_lote_distribuicao" field.</summary>
    public const int IdLoteDistribuicaoFieldNumber = 5;
    private long idLoteDistribuicao_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long IdLoteDistribuicao {
      get { return idLoteDistribuicao_; }
      set {
        idLoteDistribuicao_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RemessaProcessoFoiAgendada);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RemessaProcessoFoiAgendada other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IdProcesso != other.IdProcesso) return false;
      if (CodigoForoDestino != other.CodigoForoDestino) return false;
      if (CodigoTipoLocalDestino != other.CodigoTipoLocalDestino) return false;
      if (CodigoLocalDestino != other.CodigoLocalDestino) return false;
      if (IdLoteDistribuicao != other.IdLoteDistribuicao) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (IdProcesso.Length != 0) hash ^= IdProcesso.GetHashCode();
      if (CodigoForoDestino != 0) hash ^= CodigoForoDestino.GetHashCode();
      if (CodigoTipoLocalDestino != 0) hash ^= CodigoTipoLocalDestino.GetHashCode();
      if (CodigoLocalDestino != 0) hash ^= CodigoLocalDestino.GetHashCode();
      if (IdLoteDistribuicao != 0L) hash ^= IdLoteDistribuicao.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (IdProcesso.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(IdProcesso);
      }
      if (CodigoForoDestino != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(CodigoForoDestino);
      }
      if (CodigoTipoLocalDestino != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(CodigoTipoLocalDestino);
      }
      if (CodigoLocalDestino != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(CodigoLocalDestino);
      }
      if (IdLoteDistribuicao != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(IdLoteDistribuicao);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (IdProcesso.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(IdProcesso);
      }
      if (CodigoForoDestino != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(CodigoForoDestino);
      }
      if (CodigoTipoLocalDestino != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(CodigoTipoLocalDestino);
      }
      if (CodigoLocalDestino != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(CodigoLocalDestino);
      }
      if (IdLoteDistribuicao != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(IdLoteDistribuicao);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (IdProcesso.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdProcesso);
      }
      if (CodigoForoDestino != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CodigoForoDestino);
      }
      if (CodigoTipoLocalDestino != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CodigoTipoLocalDestino);
      }
      if (CodigoLocalDestino != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CodigoLocalDestino);
      }
      if (IdLoteDistribuicao != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(IdLoteDistribuicao);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RemessaProcessoFoiAgendada other) {
      if (other == null) {
        return;
      }
      if (other.IdProcesso.Length != 0) {
        IdProcesso = other.IdProcesso;
      }
      if (other.CodigoForoDestino != 0) {
        CodigoForoDestino = other.CodigoForoDestino;
      }
      if (other.CodigoTipoLocalDestino != 0) {
        CodigoTipoLocalDestino = other.CodigoTipoLocalDestino;
      }
      if (other.CodigoLocalDestino != 0) {
        CodigoLocalDestino = other.CodigoLocalDestino;
      }
      if (other.IdLoteDistribuicao != 0L) {
        IdLoteDistribuicao = other.IdLoteDistribuicao;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            IdProcesso = input.ReadString();
            break;
          }
          case 16: {
            CodigoForoDestino = input.ReadInt32();
            break;
          }
          case 24: {
            CodigoTipoLocalDestino = input.ReadInt32();
            break;
          }
          case 32: {
            CodigoLocalDestino = input.ReadInt32();
            break;
          }
          case 40: {
            IdLoteDistribuicao = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            IdProcesso = input.ReadString();
            break;
          }
          case 16: {
            CodigoForoDestino = input.ReadInt32();
            break;
          }
          case 24: {
            CodigoTipoLocalDestino = input.ReadInt32();
            break;
          }
          case 32: {
            CodigoLocalDestino = input.ReadInt32();
            break;
          }
          case 40: {
            IdLoteDistribuicao = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
