// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: VagasForamImpedidasParaDistribuicao.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using System.Diagnostics.CodeAnalysis;
using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Softplan.MP.DistribuicaoSegundoGrau.Domain.Distribuicoes.Messages.Protos {

  [ExcludeFromCodeCoverage]
  /// <summary>Holder for reflection information generated from VagasForamImpedidasParaDistribuicao.proto</summary>
  public static partial class VagasForamImpedidasParaDistribuicaoReflection {

    #region Descriptor
    /// <summary>File descriptor for VagasForamImpedidasParaDistribuicao.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static VagasForamImpedidasParaDistribuicaoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CilWYWdhc0ZvcmFtSW1wZWRpZGFzUGFyYURpc3RyaWJ1aWNhby5wcm90byJd",
            "CiNWYWdhc0ZvcmFtSW1wZWRpZGFzUGFyYURpc3RyaWJ1aWNhbxI2Cg92YWdh",
            "c19pbXBlZGlkYXMYASADKAsyHS5WYWdhSW1wZWRpZGFQYXJhRGlzdHJpYnVp",
            "Y2FvIlIKHFZhZ2FJbXBlZGlkYVBhcmFEaXN0cmlidWljYW8SDwoHaWRfdmFn",
            "YRgBIAEoBRIRCglkZXNjcmljYW8YAiABKAkSDgoGbW90aXZvGAMgASgJQkuq",
            "AkhTb2Z0cGxhbi5NUC5EaXN0cmlidWljYW9TZWd1bmRvR3JhdS5Eb21haW4u",
            "RGlzdHJpYnVpY29lcy5NZXNzYWdlcy5Qcm90b3NiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Softplan.MP.DistribuicaoSegundoGrau.Domain.Distribuicoes.Messages.Protos.VagasForamImpedidasParaDistribuicao), global::Softplan.MP.DistribuicaoSegundoGrau.Domain.Distribuicoes.Messages.Protos.VagasForamImpedidasParaDistribuicao.Parser, new[]{ "VagasImpedidas" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Softplan.MP.DistribuicaoSegundoGrau.Domain.Distribuicoes.Messages.Protos.VagaImpedidaParaDistribuicao), global::Softplan.MP.DistribuicaoSegundoGrau.Domain.Distribuicoes.Messages.Protos.VagaImpedidaParaDistribuicao.Parser, new[]{ "IdVaga", "Descricao", "Motivo" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class VagasForamImpedidasParaDistribuicao : pb::IMessage<VagasForamImpedidasParaDistribuicao>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<VagasForamImpedidasParaDistribuicao> _parser = new pb::MessageParser<VagasForamImpedidasParaDistribuicao>(() => new VagasForamImpedidasParaDistribuicao());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<VagasForamImpedidasParaDistribuicao> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Softplan.MP.DistribuicaoSegundoGrau.Domain.Distribuicoes.Messages.Protos.VagasForamImpedidasParaDistribuicaoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VagasForamImpedidasParaDistribuicao() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VagasForamImpedidasParaDistribuicao(VagasForamImpedidasParaDistribuicao other) : this() {
      vagasImpedidas_ = other.vagasImpedidas_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VagasForamImpedidasParaDistribuicao Clone() {
      return new VagasForamImpedidasParaDistribuicao(this);
    }

    /// <summary>Field number for the "vagas_impedidas" field.</summary>
    public const int VagasImpedidasFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Softplan.MP.DistribuicaoSegundoGrau.Domain.Distribuicoes.Messages.Protos.VagaImpedidaParaDistribuicao> _repeated_vagasImpedidas_codec
        = pb::FieldCodec.ForMessage(10, global::Softplan.MP.DistribuicaoSegundoGrau.Domain.Distribuicoes.Messages.Protos.VagaImpedidaParaDistribuicao.Parser);
    private readonly pbc::RepeatedField<global::Softplan.MP.DistribuicaoSegundoGrau.Domain.Distribuicoes.Messages.Protos.VagaImpedidaParaDistribuicao> vagasImpedidas_ = new pbc::RepeatedField<global::Softplan.MP.DistribuicaoSegundoGrau.Domain.Distribuicoes.Messages.Protos.VagaImpedidaParaDistribuicao>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Softplan.MP.DistribuicaoSegundoGrau.Domain.Distribuicoes.Messages.Protos.VagaImpedidaParaDistribuicao> VagasImpedidas {
      get { return vagasImpedidas_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as VagasForamImpedidasParaDistribuicao);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(VagasForamImpedidasParaDistribuicao other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!vagasImpedidas_.Equals(other.vagasImpedidas_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= vagasImpedidas_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      vagasImpedidas_.WriteTo(output, _repeated_vagasImpedidas_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      vagasImpedidas_.WriteTo(ref output, _repeated_vagasImpedidas_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += vagasImpedidas_.CalculateSize(_repeated_vagasImpedidas_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(VagasForamImpedidasParaDistribuicao other) {
      if (other == null) {
        return;
      }
      vagasImpedidas_.Add(other.vagasImpedidas_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            vagasImpedidas_.AddEntriesFrom(input, _repeated_vagasImpedidas_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            vagasImpedidas_.AddEntriesFrom(ref input, _repeated_vagasImpedidas_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class VagaImpedidaParaDistribuicao : pb::IMessage<VagaImpedidaParaDistribuicao>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<VagaImpedidaParaDistribuicao> _parser = new pb::MessageParser<VagaImpedidaParaDistribuicao>(() => new VagaImpedidaParaDistribuicao());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<VagaImpedidaParaDistribuicao> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Softplan.MP.DistribuicaoSegundoGrau.Domain.Distribuicoes.Messages.Protos.VagasForamImpedidasParaDistribuicaoReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VagaImpedidaParaDistribuicao() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VagaImpedidaParaDistribuicao(VagaImpedidaParaDistribuicao other) : this() {
      idVaga_ = other.idVaga_;
      descricao_ = other.descricao_;
      motivo_ = other.motivo_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VagaImpedidaParaDistribuicao Clone() {
      return new VagaImpedidaParaDistribuicao(this);
    }

    /// <summary>Field number for the "id_vaga" field.</summary>
    public const int IdVagaFieldNumber = 1;
    private int idVaga_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int IdVaga {
      get { return idVaga_; }
      set {
        idVaga_ = value;
      }
    }

    /// <summary>Field number for the "descricao" field.</summary>
    public const int DescricaoFieldNumber = 2;
    private string descricao_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Descricao {
      get { return descricao_; }
      set {
        descricao_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "motivo" field.</summary>
    public const int MotivoFieldNumber = 3;
    private string motivo_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Motivo {
      get { return motivo_; }
      set {
        motivo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as VagaImpedidaParaDistribuicao);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(VagaImpedidaParaDistribuicao other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IdVaga != other.IdVaga) return false;
      if (Descricao != other.Descricao) return false;
      if (Motivo != other.Motivo) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (IdVaga != 0) hash ^= IdVaga.GetHashCode();
      if (Descricao.Length != 0) hash ^= Descricao.GetHashCode();
      if (Motivo.Length != 0) hash ^= Motivo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (IdVaga != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(IdVaga);
      }
      if (Descricao.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Descricao);
      }
      if (Motivo.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Motivo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (IdVaga != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(IdVaga);
      }
      if (Descricao.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Descricao);
      }
      if (Motivo.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Motivo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (IdVaga != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IdVaga);
      }
      if (Descricao.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Descricao);
      }
      if (Motivo.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Motivo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(VagaImpedidaParaDistribuicao other) {
      if (other == null) {
        return;
      }
      if (other.IdVaga != 0) {
        IdVaga = other.IdVaga;
      }
      if (other.Descricao.Length != 0) {
        Descricao = other.Descricao;
      }
      if (other.Motivo.Length != 0) {
        Motivo = other.Motivo;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            IdVaga = input.ReadInt32();
            break;
          }
          case 18: {
            Descricao = input.ReadString();
            break;
          }
          case 26: {
            Motivo = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            IdVaga = input.ReadInt32();
            break;
          }
          case 18: {
            Descricao = input.ReadString();
            break;
          }
          case 26: {
            Motivo = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
