// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: VagaFoiSelecionadaParaDistribuicao.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using System.Diagnostics.CodeAnalysis;
using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Softplan.MP.DistribuicaoSegundoGrau.Domain.Distribuicoes.Messages.Protos {

  [ExcludeFromCodeCoverage]
  /// <summary>Holder for reflection information generated from VagaFoiSelecionadaParaDistribuicao.proto</summary>
  public static partial class VagaFoiSelecionadaParaDistribuicaoReflection {

    #region Descriptor
    /// <summary>File descriptor for VagaFoiSelecionadaParaDistribuicao.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static VagaFoiSelecionadaParaDistribuicaoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CihWYWdhRm9pU2VsZWNpb25hZGFQYXJhRGlzdHJpYnVpY2FvLnByb3RvGh5n",
            "b29nbGUvcHJvdG9idWYvd3JhcHBlcnMucHJvdG8ilwEKIlZhZ2FGb2lTZWxl",
            "Y2lvbmFkYVBhcmFEaXN0cmlidWljYW8SDwoHaWRfdmFnYRgBIAEoBRI6ChVp",
            "ZF9yZWdyYV9kaXN0cmlidWljYW8YAiABKAsyGy5nb29nbGUucHJvdG9idWYu",
            "SW50MzJWYWx1ZRITCgtpZF9wcm9jZXNzbxgDIAEoCRIPCgd2b2x1bWVzGAQg",
            "ASgFQkuqAkhTb2Z0cGxhbi5NUC5EaXN0cmlidWljYW9TZWd1bmRvR3JhdS5E",
            "b21haW4uRGlzdHJpYnVpY29lcy5NZXNzYWdlcy5Qcm90b3NiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Softplan.MP.DistribuicaoSegundoGrau.Domain.Distribuicoes.Messages.Protos.VagaFoiSelecionadaParaDistribuicao), global::Softplan.MP.DistribuicaoSegundoGrau.Domain.Distribuicoes.Messages.Protos.VagaFoiSelecionadaParaDistribuicao.Parser, new[]{ "IdVaga", "IdRegraDistribuicao", "IdProcesso", "Volumes" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class VagaFoiSelecionadaParaDistribuicao : pb::IMessage<VagaFoiSelecionadaParaDistribuicao>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<VagaFoiSelecionadaParaDistribuicao> _parser = new pb::MessageParser<VagaFoiSelecionadaParaDistribuicao>(() => new VagaFoiSelecionadaParaDistribuicao());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<VagaFoiSelecionadaParaDistribuicao> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Softplan.MP.DistribuicaoSegundoGrau.Domain.Distribuicoes.Messages.Protos.VagaFoiSelecionadaParaDistribuicaoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VagaFoiSelecionadaParaDistribuicao() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VagaFoiSelecionadaParaDistribuicao(VagaFoiSelecionadaParaDistribuicao other) : this() {
      idVaga_ = other.idVaga_;
      IdRegraDistribuicao = other.IdRegraDistribuicao;
      idProcesso_ = other.idProcesso_;
      volumes_ = other.volumes_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VagaFoiSelecionadaParaDistribuicao Clone() {
      return new VagaFoiSelecionadaParaDistribuicao(this);
    }

    /// <summary>Field number for the "id_vaga" field.</summary>
    public const int IdVagaFieldNumber = 1;
    private int idVaga_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int IdVaga {
      get { return idVaga_; }
      set {
        idVaga_ = value;
      }
    }

    /// <summary>Field number for the "id_regra_distribuicao" field.</summary>
    public const int IdRegraDistribuicaoFieldNumber = 2;
    private static readonly pb::FieldCodec<int?> _single_idRegraDistribuicao_codec = pb::FieldCodec.ForStructWrapper<int>(18);
    private int? idRegraDistribuicao_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int? IdRegraDistribuicao {
      get { return idRegraDistribuicao_; }
      set {
        idRegraDistribuicao_ = value;
      }
    }


    /// <summary>Field number for the "id_processo" field.</summary>
    public const int IdProcessoFieldNumber = 3;
    private string idProcesso_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IdProcesso {
      get { return idProcesso_; }
      set {
        idProcesso_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "volumes" field.</summary>
    public const int VolumesFieldNumber = 4;
    private int volumes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Volumes {
      get { return volumes_; }
      set {
        volumes_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as VagaFoiSelecionadaParaDistribuicao);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(VagaFoiSelecionadaParaDistribuicao other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IdVaga != other.IdVaga) return false;
      if (IdRegraDistribuicao != other.IdRegraDistribuicao) return false;
      if (IdProcesso != other.IdProcesso) return false;
      if (Volumes != other.Volumes) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (IdVaga != 0) hash ^= IdVaga.GetHashCode();
      if (idRegraDistribuicao_ != null) hash ^= IdRegraDistribuicao.GetHashCode();
      if (IdProcesso.Length != 0) hash ^= IdProcesso.GetHashCode();
      if (Volumes != 0) hash ^= Volumes.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (IdVaga != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(IdVaga);
      }
      if (idRegraDistribuicao_ != null) {
        _single_idRegraDistribuicao_codec.WriteTagAndValue(output, IdRegraDistribuicao);
      }
      if (IdProcesso.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(IdProcesso);
      }
      if (Volumes != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Volumes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (IdVaga != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(IdVaga);
      }
      if (idRegraDistribuicao_ != null) {
        _single_idRegraDistribuicao_codec.WriteTagAndValue(ref output, IdRegraDistribuicao);
      }
      if (IdProcesso.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(IdProcesso);
      }
      if (Volumes != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Volumes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (IdVaga != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IdVaga);
      }
      if (idRegraDistribuicao_ != null) {
        size += _single_idRegraDistribuicao_codec.CalculateSizeWithTag(IdRegraDistribuicao);
      }
      if (IdProcesso.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdProcesso);
      }
      if (Volumes != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Volumes);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(VagaFoiSelecionadaParaDistribuicao other) {
      if (other == null) {
        return;
      }
      if (other.IdVaga != 0) {
        IdVaga = other.IdVaga;
      }
      if (other.idRegraDistribuicao_ != null) {
        if (idRegraDistribuicao_ == null || other.IdRegraDistribuicao != 0) {
          IdRegraDistribuicao = other.IdRegraDistribuicao;
        }
      }
      if (other.IdProcesso.Length != 0) {
        IdProcesso = other.IdProcesso;
      }
      if (other.Volumes != 0) {
        Volumes = other.Volumes;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            IdVaga = input.ReadInt32();
            break;
          }
          case 18: {
            int? value = _single_idRegraDistribuicao_codec.Read(input);
            if (idRegraDistribuicao_ == null || value != 0) {
              IdRegraDistribuicao = value;
            }
            break;
          }
          case 26: {
            IdProcesso = input.ReadString();
            break;
          }
          case 32: {
            Volumes = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            IdVaga = input.ReadInt32();
            break;
          }
          case 18: {
            int? value = _single_idRegraDistribuicao_codec.Read(ref input);
            if (idRegraDistribuicao_ == null || value != 0) {
              IdRegraDistribuicao = value;
            }
            break;
          }
          case 26: {
            IdProcesso = input.ReadString();
            break;
          }
          case 32: {
            Volumes = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
